### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by cleitonjohnson** [cristianbuse/VBA-UserForm-MouseScroll#21]
if copy and paste the code ![image](https://user-images.githubusercontent.com/68911422/206867331-16a5c1bb-20a0-4dcf-8c32-fcf3ae2c7769.png)

if import the file
![image](https://user-images.githubusercontent.com/68911422/206867381-3eac6beb-4c04-47c4-943a-81868b3e5b5c.png)

**Comment by cleitonjohnson** [comment]
The VBA UserForm MouseScroll_DEMO run normally

**Comment by cristianbuse** [comment]
Hi @cleitonjohnson ,

Don't copy paste the code. Clone the repository or dowload the [zip](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/archive/refs/heads/master.zip) file and then import the modules.

**Comment by cleitonjohnson** [comment]
The file imported from the zip folder works.
But interesting that copied from the DEMO file does not work.
Which magic has the most inside that imported file there? :-D
![report5](https://user-images.githubusercontent.com/68911422/206868649-93b27b97-b2be-4b4b-a787-688dce56bfe3.gif)
![report6](https://user-images.githubusercontent.com/68911422/206868651-bf43ad62-35c4-4322-8003-65ae3c780dcc.gif)

**Comment by cristianbuse** [comment]
Hi @cleitonjohnson ,

VB* modules have hidden attributes that you can only see in a text editor. For example the top 9 lines in the [class module](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/blob/31978bd0dca0bd9505573666fdca4a8869864cdf/src/MouseOverControl.cls) are clearly visible as text but when you import the module, you won't see them in the IDE. This is unfortunately one of the many issues with the VBA editor. So, copy-paste does not work in this case because you need the special ```Attribute VB_PredeclaredId = True``` but when copy-pasting it gets defaulted to ```False```.
