### ISSUE TITLE
Crashes with no error message

### ISSUE THREAD

**Issue by Cosmic-78** [cristianbuse/VBA-UserForm-MouseScroll#22]
After Office updated today (2023/01/13), attempting to run any form which has the mouse scroll enabled causes Excel to completely crash and reload with no error message.  Best I can tell, the crash seems to happen when this line is called `m_hHookMouse = SetWindowsHookEx(WH_MOUSE, AddressOf MouseProc, 0, GetCurrentThreadId())` in the `HookMouse()` function.  Prior to the updates, the code ran fine.  The version information on my copy of Excel is Microsoft® Excel® for Microsoft 365 MSO (Version 2212 Build 16.0.15928.20196) 64-bit running on Windows 10 64 Bit Enterprise (Version 1909 Build 18363.2274), i7 processor with 32GB ram

**Comment by cristianbuse** [comment]
@Cosmic-78 I was able to upgrade to version 2208 which is the latest version that my subscription has. Unfortunately, I was not able to replicate the issue. I will leave this issue open for now and I will try to get my hands on version 2212.

You could try this:
- comment out all the ```EnableMouseScroll``` lines
- delete the scroll modules (MouseScroll.bas and MouseOverControl.cls)
- run your code (forms won't scroll of course)
- save file and close
- open file
- import back the scroll modules
- uncomment all the ```EnableMouseScroll``` lines
- try running and see if crashes still occur
This should cover the case where code got corrupted by the edit-and-continue feature, since it rewrites chunks of p-code on the fly.

**Comment by Cosmic-78** [comment]
I followed the steps above and imported copies of the latest version and it appears to function just fine now, so I've closed this issue.  Thank you for taking the time to help.
